### ISSUE TITLE
Error during cluster_setup_network playbook execution with dedicated interface for PTP

### ISSUE THREAD

**Issue by pierrickmolera** [seapath/ansible#422]
**Describe the bug**
When I'm executing Ansible playbook for cluster network installation with dedicated network interface for PTP,
the first time execution is stopped with error.
To continue I need to reboot each node and the installation of network can be achieved

**To Reproduce**
1. Prepare PTP on your deploy machine with dedicated network interface with specific vlan
2. Perpare your Ansible inventory and give the dedicated network interface on your node
``` 
ptp_interface: "enp88s0" #OPTIONAL PTP Interface
ptp_vlanid: 503 #OPTIONAL VlanID for PTP
ptp_delay_mechanism: E2E # OPTIONAL E2E or P2P defaut is P2P
ptp_network_transport: L2 # OPTIONAL L2 or UDPv4 default is L2 
```
3. install cluster prequisite playbook
4. install cluster netwok playbook
5. See error

**Expected behavior**
Ansible manage automatically the error and reboot the nodes itself if needed after network changes

**Screenshots**
<img width="582" alt="seapath_erreur_network1" src="https://github.com/seapath/ansible/assets/73014265/5b109f3f-df83-46df-aab4-19cd8e2be8c7">
<img width="642" alt="seapath_erreur_network2" src="https://github.com/seapath/ansible/assets/73014265/b323e6c8-32a7-4972-a90e-25b247b9a757">

**Nodes configuration:**
 - Nuc Intel
 - OS : Debian 12

**Comment by insatomcat** [comment]
The ptp_vlanid variable is used for the PTP configuration (obviously). 
But it's not use for network configuration!

You still need to create the vlan interface on the appropriate nic.

For that you're supposed to used the custom_netdev and custom_network inventory variable, like:

```
custom_netdev:
  00-vlan100:
    - NetDev:
      - Name: "{{ ptp_interface + '.' + ptp_vlanid|string }}"
      - Kind: "vlan"
    - VLAN:
      - Id: "{{ ptp_vlanid }}"
custom_network:
  - 01-physicalptpinterface:
    - Match:
      - Name: "{{ ptp_interface }}"
      - Type: "ether"
    - Network:
      - VLAN: "{{ ptp_interface + '.' + ptp_vlanid|string }}"
      - Description: "ptp interface {{ ptp_interface }} vlan {{ ptp_vlanid }}"
```
