### ISSUE TITLE
Team0 network is needed when deploying a Seapath Debian standalone machine

### ISSUE THREAD

**Issue by Paullgk** [seapath/ansible#689]
**Describe the bug**
When deploying a Seapath Standalone machine (without cluster features), some task need the team0 network. It should not, as it make no sense to have a cluster network on a standalone machine.

**To Reproduce**
Deploy a Standalone configuration, without cluster features.

```
ok: [hypervisor]
TASK [debian hypervisor : Create ovs-vswitchd. service drop-in]Thursday 16 January 2025
13:20:21 +0000 (0:00:00.158)
0:00:30.599 ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors. AnsibleUndefinedVariable: 'teamo_O' is undefined fatal: [hypervisor]: FAILED! → changed=false
nged-false e undefined.
msg: 'AnsibleUndefinedVariable: ''teamo_O'' is undefined'
TASK [debian hypervisor : Create ovs-vswitchd. service drop-in]An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors. AnsibleUndefinedVariable: 'teamo_O' is undefined fatal: [hypervisor]: FAILED! → changed=false
nged-false e undefined.
msg: 'AnsibleUndefinedVariable: ''teamo_O'' is undefined'
```

**Expected behavior**
No cluster configuration are needed when deploying a standalone configuration.

**Screenshots**

**Desktop (please complete the following information):**
- Standalone machine

**Additional context**
The issue seems to be introduced by https://github.com/seapath/ansible/pull/666
More precisely, in `roles/debian_hypervisor/tasks/main.yml`:

```yaml
- name: Copy team0_x@.service file
  ansible.builtin.copy:
    src: team0_x@.service
    dest: /etc/systemd/system/team0_x@.service
    owner: root
    group: root
    mode: 0644
  register: team0_x_service
```

should be:

```yaml
- name: Create ovs-vswitchd.service drop-in
  template:
    src: ovs-vswitchd_override.conf.j2
    dest: /etc/systemd/system/ovs-vswitchd.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  register: ovsvswitchd
  when: team0_0 is defined
- name: Copy team0_x@.service file
  ansible.builtin.copy:
    src: team0_x@.service
    dest: /etc/systemd/system/team0_x@.service
    owner: root
    group: root
    mode: 0644
  register: team0_x_service
  when: team0_0 is defined
```
